- name: Deploy RKE2
  hosts: all
  become: yes
  vars:
    rke2_custom_registry_mirrors:
      - name: docker.io
        endpoint: {https://<Custome-Registry-Address>}
      - name: quay.io
        endpoint: {https://<Custome-Registry-Address>}
    rke2_cni: #cilium or docker or containerd
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
    disable_apiserver: true
    disable_controller_manager: true
    disable_scheduler: true

  roles:
     - role: ansible-role-rke2